# RFM Customer Segmentation

## Data Loading

In [5]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

password = "password"

engine = create_engine(f"mysql+pymysql://root:{password}@localhost/retail_analysis")

df = pd.read_sql("SELECT * FROM orders", engine)

df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52

In [3]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

## Feature Engineering

In [7]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [9]:
snapshot_date = df['order_date'].max() + pd.Timedelta(days=1)

## Segmentation

In [11]:
rfm = df.groupby('customer_id').agg({
    'order_date': lambda x: (snapshot_date - x.max()).days,
    'order_id': 'nunique',
    'sales': 'sum'
}).reset_index()

rfm.columns = ['customer_id', 'Recency', 'Frequency', 'Monetary']

rfm.head()

  customer_id  Recency  Frequency  Monetary
0    AA-10315      185          5   5563.56
1    AA-10375       20          9   1056.39
2    AA-10480      260          4   1782.87
3    AA-10645       56          6   4455.90
4    AB-10015      416          3    886.15

In [13]:
rfm['R_score'] = pd.qcut(rfm['Recency'], 5, labels=[5,4,3,2,1])
rfm['F_score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1,2,3,4,5])
rfm['M_score'] = pd.qcut(rfm['Monetary'], 5, labels=[1,2,3,4,5])

rfm['RFM_score'] = rfm['R_score'].astype(str) + \
                   rfm['F_score'].astype(str) + \
                   rfm['M_score'].astype(str)

rfm.head()

  customer_id  Recency  Frequency  Monetary R_score F_score M_score RFM_score
0    AA-10315      185          5   5563.56       2       2       5       225
1    AA-10375       20          9   1056.39       5       5       2       552
2    AA-10480      260          4   1782.87       1       1       3       113
3    AA-10645       56          6   4455.90       3       3       5       335
4    AB-10015      416          3    886.15       1       1       1       111

In [15]:
def segment_customer(row):
    if row['RFM_score'] in ['555','554','545','544']:
        return 'Champions'
    elif row['F_score'] == 5:
        return 'Loyal Customers'
    elif row['R_score'] == 5:
        return 'Recent Customers'
    elif row['R_score'] <= 2 and row['F_score'] <= 2:
        return 'At Risk'
    else:
        return 'Others'

rfm['Segment'] = rfm.apply(segment_customer, axis=1)

rfm['Segment'].value_counts()

Segment
Others              350
At Risk             170
Loyal Customers     123
Recent Customers     95
Champions            55
Name: count, dtype: int64

In [17]:
segment_revenue = rfm.merge(
    df.groupby('customer_id')['sales'].sum().reset_index(),
    on='customer_id'
)

segment_summary = segment_revenue.groupby('Segment').agg({
    'sales': 'sum',
    'customer_id': 'count'
}).reset_index()

segment_summary

            Segment       sales  customer_id
0           At Risk   267301.89          170
1         Champions   277594.35           55
2   Loyal Customers   503528.51          123
3            Others  1042580.91          350
4  Recent Customers   181444.41           95

In [19]:
rfm.to_sql('customer_rfm', engine, if_exists='replace', index=False)

793